name: urlshortener_v1
version: 0.0.0
description: >
  API client library for urlshortener for use with Streamy RPC framework.
authors:
- Streamy
homepage: http://code.google.com/apis/urlshortener/v1/getting_started.html
environment:
  sdk: '>=1.0.0'
dependencies:
  browser: any
  args: ">=0.9.0"
  meta: ">=0.8.8"
  fixnum: ">=0.9.0"
  json: ">=0.9.0"
  observe: ">=0.9.1"
  protobuf:
    path: ../../dart-protobuf
  streamy:
    path: ..
  quiver: ">=0.14.0"
